# Generated by Django 3.1 on 2020-08-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
