# Generated by Django 3.1 on 2020-09-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_todo_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='bucket_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
